### ISSUE TITLE
The user is shown (via the application UI) a frequency and a note, which is the result of analyzing the current microphone audio data. With no current audio data, these fields are blanked out. When there is any noise, the fields are filled in with the analysis data. This will be referred to as “live capture”, current audio analysis and nothing else (guitar tuner functionality)

### ISSUE THREAD

**Issue by Rushali** [Ilahsur/MusicRethinking#3]

**Comment by dombarrett** [comment]
This is the start of the "core" functionality. Running example (and inspiration for the project) can be found here:

[https://webaudiodemos.appspot.com/pitchdetect/index.html](https://webaudiodemos.appspot.com/pitchdetect/index.html)


Also adding this link I found. Haven't fully read it yet, but may be useful for later:

[https://hackernoon.com/a-web-audio-experiment-666743e16679#.xwuv5l4re](https://hackernoon.com/a-web-audio-experiment-666743e16679#.xwuv5l4re)

**Comment by dombarrett** [comment]
Closed. This is mostly provided from the web audio demo we are working from. It has been successfully integrated into tone.js and p5.sound workflows.
