### ISSUE TITLE
***User can use UI element to load pre-recorded audio for analysis. Upon activation, the user selects the audio file via native file management so the application can analyze it.

### ISSUE THREAD

**Issue by Rushali** [Ilahsur/MusicRethinking#8]

**Comment by dombarrett** [comment]
Rune and Patrick made a comment about this user story in class. The "***" was a reminder. They said that this might need more details, or split into separate user stories. Specifically, about what kinds of audio files are compatible, what gets clicked to prompt the action, etc.
